apiVersion: v1
kind: ConfigMap
metadata:
  name: wave-config
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
  labels:
    app.kubernetes.io/name: wave-autoscale-config
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: wave-autoscale-enterprise
data:
    {{- (tpl (.Files.Glob "config/wave-config.yaml").AsConfig . ) | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wave-definition
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
  labels:
    app.kubernetes.io/name: wave-autoscale-definition
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: definition
    app.kubernetes.io/part-of: wave-autoscale-enterprise
data:
  wave-definition.yaml: |