apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-autoscale-postgres
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
  labels:
    app.kubernetes.io/name: wave-autoscale-postgres
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wave-autoscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wave-autoscale-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wave-autoscale-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:{{ .Values.postgres.version }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.postgresDatabase }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
              subPath: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: wa-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wa-pvc
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
  labels:
    app.kubernetes.io/name: wave-autoscale-postgres-pvc
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: wave-autoscale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wave-autoscale-postgres-service
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
  labels:
    app.kubernetes.io/name: wave-autoscale-postgres-service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: wave-autoscale
spec:
  selector:
    app.kubernetes.io/name: wave-autoscale-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432