apiVersion: v1
kind: ServiceAccount
metadata:
  name: wave-autoscale-sa
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
