kind: Metric
id: wa_sample_metric_k8s_json_patch_istio_retry
collector: wa-generator
enabled: true
metadata:
  pattern: [30, 70]
  gap_seconds: 10
---
kind: ScalingComponent
id: wa_sample_component_k8s_json_patch_istio_retry
enabled: true
component_kind: kubernetes-json-patch
---
kind: ScalingPlan
id: wa_sample_plan_k8s_json_patch_istio_retry
metadata:
  title: "Sample Scaling Plan - k8s istio virtual service retry"
  cool_down: 0 # seconds
  interval: 10000 # milliseconds
enabled: true
variables:
  metric: |
    get({
        metric_id: 'wa_sample_metric_k8s_json_patch_istio_retry'
    })
plans:
  - id: add-istio-retry
    # JavaScript expression that returns a boolean value.
    expression: $metric >= 70
    # Higher priority values will be checked first.
    priority: 2
    scaling_components:
      - component_id: wa_sample_component_k8s_json_patch_istio_retry
        namespace: istio-system
        name: wa-sample-json-patch-istio-vs
        api_version: networking.istio.io/v1beta1
        kind: VirtualService
        json_patch:
          - op: add
            path: /spec/http/0/retries
            value: { "attempts": 3, "perTryTimeout": "2s" }
  - id: remove-istio-retry
    # JavaScript expression that returns a boolean value.
    expression: $metric < 70
    # Higher priority values will be checked first.
    priority: 1
    scaling_components:
      - component_id: wa_sample_component_k8s_json_patch_istio_retry
        namespace: istio-system
        name: wa-sample-json-patch-istio-vs
        api_version: networking.istio.io/v1beta1
        kind: VirtualService
        json_patch:
          - op: replace
            path: /spec/http/0/retries
            value: null
