kind: Metric
id: wa_sample_metric_k8s_json_patch
collector: wa-generator
enabled: true
metadata:
  pattern: [30, 70]
  gap_seconds: 10
---
kind: ScalingComponent
id: wa_sample_k8s_json_patch
enabled: true
component_kind: kubernetes-json-patch
---
kind: ScalingPlan
id: wa_sample_k8s_istio_vs_delay
metadata:
  title: "Sample Scaling Plan - k8s istio virtual service dely"
  cool_down: 0 # seconds
  interval: 10000 # milliseconds
enabled: true
variables:
  metric: |
    get({
        metric_id: 'wa_sample_metric_k8s_json_patch'
    })
plans:
  - id: add-istio-fault-injection
    # JavaScript expression that returns a boolean value.
    expression: $metric >= 70
    # Higher priority values will be checked first.
    priority: 2
    scaling_components:
      - component_id: wa_sample_k8s_json_patch
        namespace: istio-system
        name: wa-sample-istio-vs
        api_version: networking.istio.io/v1beta1
        kind: VirtualService
        json_patch:
          - op: add
            path: /spec/http/0/fault
            value: { "delay": { "fixedDelay": 10s } }
          - op: add
            path: /spec/http/0/fault/delay/percentage
            value: { "value": 100 }
  - id: remove-istio-fault-injection
    # JavaScript expression that returns a boolean value.
    expression: $metric < 70
    # Higher priority values will be checked first.
    priority: 1
    scaling_components:
      - component_id: wa_sample_k8s_json_patch
        namespace: istio-system
        name: wa-sample-istio-vs
        api_version: networking.istio.io/v1beta1
        kind: VirtualService
        json_patch:
          - op: replace
            path: /spec/http/0/fault
            value: null
