#!/usr/bin/env bash
set -eo pipefail

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

moon sync projects
cargo audit --ignore RUSTSEC-2022-0090 --ignore RUSTSEC-2020-0071
moon run :lint