// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AutoscalingHistoryDefinition {
  id: string;
  plan_db_id: string;
  plan_id: string;
  plan_item_json: string;
  metric_values_json: string;
  metadata_values_json: string;
  fail_message: string | null;
}
