// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EC2AutoscalingMetadata { region: string, access_key: string | null, secret_key: string | null, asg_name: string, }