// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface K8sDeploymentMetadata { api_server_endpoint: string, namespace: string, name: string, }