// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PlanItemDefinition { id: string, description: string, expression: string, priority: number, scaling_components: Array<object>, ui: any, }