// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrometheusMetricMetadata { query: string, prometheus_url: string, prometheus_token: string | null, polling_interval: number, }