// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectKind } from "./object-kind";

export interface ScalingComponentDefinition { kind: ObjectKind, db_id: string, id: string, component_kind: string, metadata: object, enabled: boolean, }