name: CI - Integration Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # on Pull Request
  pull_request:
    branches:
      - "main"
  # on Push
  push:
    branches:
      - "main"
      - "release-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  integration-test:
    if: github.repository == 'stclab-inc/wave-autoscale'
    runs-on: wave-autoscale-runner
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        timeout-minutes: 1
        with:
          fetch-depth: 0

      #
      # Dependencies
      #
      - name: Install Moonrepo
        uses: moonrepo/setup-moon-action@v1

      - name: Set up moon cache
        uses: actions/cache@v3
        continue-on-error: false
        timeout-minutes: 10
        with:
          path: |
            .moon/cache/
          key: ${{ runner.os }}-moon-${{ hashFiles('**/moon.yml','.moon/**/*') }}
          restore-keys: |
            ${{ runner.os }}-moon-

      - name: Install Clippy
        run: rustup component add clippy

      # WORKAROUND: moon 1.13.2 has a bug of cargo binstall
      - name: Install BInstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo-nextest
        run: cargo binstall -y cargo-nextest

      - name: Install cargo-cache
        run: cargo binstall -y cargo-cache

      - name: Install cargo-deny
        run: cargo binstall -y cargo-deny
      ## END OF WORKAROUND

      #
      # Licenses, Bans
      #
      - name: Cargo-deny Check (Licenses, Bans)
        run: cargo deny check licenses ban

      #
      # Test
      #
      - name: Run test
        run: moon run controller:test -f

      # Clean up
      - name: Cargo Autoclean
        run: moon run cmd:clean-cargo-cache -f
